version: '3'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.0
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_HOST: 84.38.181.86
      MYSQL_DATABASE: linerfin
      MYSQL_USERNAME: dev
      MYSQL_PASSWORD: rrdJxkFiSjup1
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    env_file:
      - .env
    working_dir: /var/www/
    volumes:
      - /var/www/:/var/www/
        #      - /var/www/linercrm.r:/var/www/linercrm.ru
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    #    command: bash -c "chmod 777 -R /var/www"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/www/:/var/www/
      - /var/www/terminal.linercrm.ru/:/var/www/terminal.linercrm.ru/
        #      - /var/www/linerfin.ru/:/var/www/linerfin.ru
        #      - /var/www/linercrm.ru/:/var/www/linercrm.ru
      - /etc/letsencrypt/live/linercrm.ru/fullchain.pem:/etc/letsencrypt/live/linercrm.ru/fullchain.pem
      - /etc/letsencrypt/live/linercrm.ru/privkey.pem:/etc/letsencrypt/live/linercrm.ru/privkey.pem
      - /etc/letsencrypt/live/linerfin.ru/privkey.pem:/etc/letsencrypt/live/linerfin.ru/privkey.pem
      - /etc/letsencrypt/live/linerfin.ru/fullchain.pem:/etc/letsencrypt/live/linerfin.ru/fullchain.pem
      - /etc/letsencrypt/live/auth.linerfin.ru/fullchain.pem:/etc/letsencrypt/live/auth.linerfin.ru/fullchain.pem
      - /etc/letsencrypt/live/auth.linerfin.ru/privkey.pem:/etc/letsencrypt/live/auth.linerfin.ru/privkey.pem
      - /etc/letsencrypt/live/linerfin.ru-0001/fullchain.pem:/etc/letsencrypt/live/linerfin.ru-0001/fullchain.pem
      - /etc/letsencrypt/live/linerfin.ru-0001/privkey.pem:/etc/letsencrypt/live/linerfin.ru-0001/privkey.pem
    networks:
      - app-network

  backup:
    image: schickling/mysql-backup-s3
    restart: always
    environment:
      SCHEDULE: '@daily'
      BACKUP_KEEP_DAYS: 14
      S3_ENDPOINT: https://storage.clo.ru/
      S3_REGION: eu-north-1
      S3_ACCESS_KEY_ID: JQI40JRCY20TZ06N0O1U
      S3_SECRET_ACCESS_KEY: 8sBBkoOzI2tglutRetHZ2sTgCb2UpM8qgh3BDSVA
      S3_BUCKET: apps3tablecrm-default-bucket
      S3_PREFIX: backups/linerfin
      MYSQL_HOST: 84.38.181.86
      MYSQL_USER: dev
      MYSQL_PASSWORD: rrdJxkFiSjup1
    networks:
      - app-network

  # MySQL Service
  db:
   image: mysql:5.7.22
   volumes:
           #  - /opt/linerfinru/linerfinru.sql:/var/
      - /var/lib/:/var/lib/
        #  - ./mysql/my.cnf:/etc/mysql/my.cnf
   container_name: db
   restart: unless-stopped
   tty: true
   ports:
      - "3307:3306"
   environment:
      MYSQL_DATEBASE: linerfin
      MYSQL_USERNAME: dev
      MYSQL_PASSWORD: rrdJxkFiSjup1
   env_file:
      - .env
   networks:
      - app-network

# Docker Networks
networks:
  app-network:
    driver: bridge
