version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: linerfin_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      DB_HOST: db
      DB_PORT: 3306
    env_file:
      - .env.dev
    depends_on:
      - db
      - redis
    networks:
      - linerfin-network

  webserver:
    image: nginx:alpine
    container_name: linerfin_nginx
    restart: unless-stopped
    ports:
      - "8085:80"
      - "5443:443"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - linerfin-network

  db:
    image: mysql:8.0
    container_name: linerfin_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: linerfin
      MYSQL_USER: dev
      MYSQL_PASSWORD: rrdJxkFiSjup1
      MYSQL_ROOT_PASSWORD: rootpassword123
    volumes:
      - mysql_data:/var/lib/mysql
      #- ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    networks:
      - linerfin-network

  redis:
    image: redis:alpine
    container_name: linerfin_redis
    restart: unless-stopped
    ports:
      - "6378:6379"
    networks:
      - linerfin-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: linerfin_pma
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8086:80"
    depends_on:
      - db
    networks:
      - linerfin-network

volumes:
  mysql_data:

networks:
  linerfin-network:
    driver: bridge
