#server {
#    listen 80;
#    server_name _;
#    root /var/www/public;
#    index index.php;
#    
#    location / {
#        try_files $uri $uri/ /index.php?$query_string;
#    }
#    
#    location ~ \.php$ {
#        fastcgi_pass app:9000;
#        fastcgi_index index.php;
#        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#        include fastcgi_params;
#    }
#}
server {
    listen 80;
    server_name linerfin.ru *.linerfin.ru;
    root /var/www/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }
}

# Перенаправление с www
server {
    listen 80;
    server_name www.linerfin.ru;
    return 301 $scheme://linerfin.ru$request_uri;
}
