#server {
#    listen 80;
#    server_name _;
#    root /var/www/public;
#    index index.php;
#    
#    location / {
#        try_files $uri $uri/ /index.php?$query_string;
#    }
#    
#    location ~ \.php$ {
#        fastcgi_pass app:9000;
#        fastcgi_index index.php;
#        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
#        include fastcgi_params;
#    }
#}
server {
    listen 80;
    server_name linerfin.local *.linerfin.local;
    root /var/www/public;
    index index.php;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
	fastcgi_connect_timeout 300;
	fastcgi_send_timeout 300;
	fastcgi_read_timeout 300;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    # Логи для отладки поддоменов
    access_log /var/log/nginx/linerfin_access.log;
    error_log /var/log/nginx/linerfin_error.log;
}

# Перенаправление с www
server {
    listen 80;
    server_name www.linerfin.local;
    return 301 $scheme://linerfin.local$request_uri;
}
